---
name: HCP Boundary Egress worker configuration
command: |-
  sudo tee {{file}} > /dev/null << EOF
  disable_mlock = true

  listener "tcp" {
    address = "0.0.0.0:9203"
    purpose = "proxy"
  }

  worker {
    initial_upstreams = ["{{upstream}}:9202"]
    auth_storage_path = "/opt/boundary/egress-worker"
    tags {
      type = ["egress"]
    }
  }
  EOF
tags:
  - boundary
description: Creates the configuration for the egress worker
arguments:
  - name: file
    description: The output file
    default_value: /etc/boundary.d/egress-worker.hcl
  - name: upstream
    description: The external IP address of the ingress worker to connect to
    default_value: 1.2.3.4
author: Chris van Meer
author_url: https://chrisvanmeer.nl
shells: []
